config/routes.rb
Rails.application.routes.draw do
  get 'work/index'
  get 'work/choose_theme'
  get 'work/display_theme'

  resources :users, only: [:show, :create]
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'main/index'
  get 'main/help'

  namespace :api, defaults: { format: :json } do
      match 'next_image',       to: 'api#next_image',   via: 'get'
      match 'prev_image',       to: 'api#prev_image',   via: 'get'
      match 'save_value',       to: 'api#save_value',   via: :get
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # work
  match 'work',             to: 'work#index',             via: :get
  match 'choose_theme',     to: 'work#choose_theme',      via: :get
  match 'display_theme',    to: 'work#display_theme',     via: :post
  match 'results_list',     to: 'work#results_list', via: :get

  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'delete'

  root 'main#index'
end

app/models/user.rb
class User < ApplicationRecord
    has_many :values, dependent: :destroy

    # before_save { self.email = email.downcase }
    before_save { email.downcase! } # alternative
    before_create :create_remember_token

    validates :name, presence: true, uniqueness: true, length: { maximum: 50 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

    has_secure_password

    validates :password, length: { minimum: 6 }

    def User.new_remember_token
        SecureRandom.urlsafe_base64
    end

    def User.encrypt(token)
        Digest::SHA1.hexdigest(token.to_s)
    end

    private

    def create_remember_token
        self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, size = 120)
        hash =Digest::MD5::hexdigest(user.email.downcase)
         
        default = "wavatar"

        # Compile the full URL with URI encoding for the parameters
        params = URI.encode_www_form('d' => default, 's' => size)
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?#{params}"

        image_tag(gravatar_url, alt: user.name, class: "gravatar rounded-circle", size: "#{size}x#{size}")
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2>
        <%= pluralize(user.errors.count, "error" ) %> prohibited this user from being saved:
      </h2>

      <ul>
        <% user.errors.each do |error| %>
          <li>
            <%= error.full_message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row g-3">
    <div class="col-12">
      <%= form.label :name, t(".name"), class: "form-label" %>
      <%= form.text_field :name, class: "form-control", type: "text", placeholder: "", value: "" %>
    </div>

    <div class="col-12">
      <%= form.label :email, t(".email"), class: "form-label" %>
      <%= form.text_field :email, class: "form-control", type: "email", placeholder: "you@example.com" %>
    </div>

    <div class="col-6">
      <%= form.label :password, t(".password"), class: "form-label" %>
      <%= form.text_field :password, class: "form-control", type: "password", placeholder: "" %>
    </div>

    <div class="col-6">
      <%= form.label :password_confirmation, t(".password_confirmation"), class: "form-label" %>
      <%= form.text_field :password_confirmation, class: "form-control", type: "password", placeholder: "" %>
    </div>


    <hr class="my-4">
    <%= form.submit t(".create_account"), class: "w-100 btn btn-primary btn-lg" %>
<% end %>


       

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<div class="row g-5">
    <div class="col-6 py-3">
        <h4 class="mb-3"><%= t(".new_user_sign_up")%></h4>
        <%= render "form" , user: @user %>
    </div>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="show_user">
  <div class="row">
    <aside class="span4">
      <section>
        <h1><%= gravatar_for @user %> <%= @user.name %></h1>
      </section>
    </aside>
  </div>
  <p>
    <b>Email</b> <%= @user.email %>
  </p>

  <%= link_to "Work", work_path, class: "btn btn-lg btn-primary" %>
</div>