config/routes.rb
Rails.application.routes.draw do
  get 'work/index'
  get 'work/choose_theme'
  get 'work/display_theme'

  resources :users, only: [:show, :create]
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'main/index'
  get 'main/help'

  namespace :api, defaults: { format: :json } do
      match 'next_image',       to: 'api#next_image',   via: 'get'
      match 'prev_image',       to: 'api#prev_image',   via: 'get'
      match 'save_value',       to: 'api#save_value',   via: :get
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # work
  match 'work',             to: 'work#index',             via: :get
  match 'choose_theme',     to: 'work#choose_theme',      via: :get
  match 'display_theme',    to: 'work#display_theme',     via: :post
  match 'results_list',     to: 'work#results_list', via: :get

  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'delete'

  root 'main#index'
end

app/views/shared/_footer.html.erb
<div class="container fixed-bottom bg-white">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top ">
    <p class="col-md-4 mb-0 text-body-secondary">&copy; 2024 Rubyonov</p>

    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item">
        <%= link_to t(".home") , main_index_path, class: "nav-link px-2 text-body-secondary" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".help") , main_help_path, class: "nav-link px-2 text-body-secondary" %>
      </li>
    </ul>
  </footer>
</div>

app/views/shared/_head.html.erb
<title>Rubyonov</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: 'all', "data-turbolinks-track": "reload" %>
<%= javascript_importmap_tags %>
<%= favicon_link_tag "favicon.ico" %>

app/views/shared/_header.html.erb
<div class="container fixed-top bg-white">
  <header
    class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      <li>
        <%= link_to t(".home") , main_index_path, class: "nav-link px-2" %>
      </li>
      <li>
        <%= link_to t(".help") , main_help_path, class: "nav-link px-2" %>
      </li>
    </ul>

    <p class="locale">
      <%= link_to image_tag("Russia.jpg", alt: "" , style: "width: 10%; height: 10%" , title: "Русский" ), locale: :ru %>
      <%= link_to image_tag("United_Kingdom.jpg", alt: "" , style: "width: 12%; height: 12%" , title: "English" ), locale: :en %>
      <%= I18n.locale %>
    </p>

    <div>
      <% if signed_in? %>
        <div class="dropdown text-end">
          <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown"
            aria-expanded="false">
            <%= gravatar_for current_user, "32x32" %>
          </a>
          <ul class="dropdown-menu text-small">
            <li>
              <%= link_to t('.profile'), current_user, class: "dropdown-item" %>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <%= link_to t('.sign_out') , signout_path, method: "delete" , class: "dropdown-item" %>
          </ul>
        </div>
        <% else %>
          <div class="text-end">
            <%= link_to t('.sign_in'), signin_path, class: "btn btn-outline-dark me-2" %>
            <%= link_to t('.sign_up'), signup_path, class: "btn btn-warning" %>
          </div>
        <% end %>
    </div>
  </header>
</div>