config/routes.rb
Rails.application.routes.draw do
  get 'work/index'
  get 'work/choose_theme'
  get 'work/display_theme'

  resources :users, only: [:show, :create]
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'main/index'
  get 'main/help'

  namespace :api, defaults: { format: :json } do
      match 'next_image',       to: 'api#next_image',   via: 'get'
      match 'prev_image',       to: 'api#prev_image',   via: 'get'
      match 'save_value',       to: 'api#save_value',   via: :get
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # work
  match 'work',             to: 'work#index',             via: :get
  match 'choose_theme',     to: 'work#choose_theme',      via: :get
  match 'display_theme',    to: 'work#display_theme',     via: :post
  match 'results_list',     to: 'work#results_list', via: :get

  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'delete'

  root 'main#index'
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :theme
    has_many :value, dependent: :destroy

    # get images array of arrays by given theme_id
    scope :theme_images, -> (theme_id) { 
        select('id','name','file','ave_value').where(theme_id: theme_id) 
    }

    # find image by id
    scope :find_image, -> (image_id) { find(image_id) }

    # calc ave_value and update to Image (image_id, ave_value)
    def self.update_ave_value(image_id, ave_value)
        image = find(image_id)
        image.update(ave_value: ave_value)
    end

    # Refactored method - transferred from work_image.rb module
    def self.show_valued_image(new_value_data)
        image_id = new_value_data[:image_id]
        theme_id = new_value_data[:theme_id]
        current_user_id = new_value_data[:user_id]
        user_valued, value = Value.user_valued_exists(current_user_id, image_id) # 1/0 ?
        values_qty = Value.all.count.round

        common_ave_value = user_valued == 1 ? find(image_id).ave_value.round : 0

        data = {
            values_qty: values_qty,
            current_user_id: current_user_id,
            theme_id: theme_id,
            image_id: image_id,
            user_valued: user_valued,
            value: value,
            common_ave_value: common_ave_value
        }
        # logger.info "In show_image:  data = #{data.inspect} "
        data
    end


    def self.value_and_update(new_value_data)
        image_id = new_value_data[:image_id]
        Value.create(new_value_data)
        ave_value = Value.calc_average_value(image_id).round
        # puts "in value_and_update: image_id = #{image_id}, ave_value = #{ave_value} \n"
        update_ave_value(image_id, ave_value)

        show_valued_image(new_value_data)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to image_url(@image), notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to image_url(@image), notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy!

    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:name, :file, :ave_value, :theme_id)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image) do |form| %>
  <% if image.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :file, style: "display: block" %>
    <%= form.text_field :file %>
  </div>

  <div>
    <%= form.label :ave_value, style: "display: block" %>
    <%= form.text_field :ave_value %>
  </div>

  <div>
    <%= form.label :theme_id, style: "display: block" %>
    <%= form.number_field :theme_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/images/_image.html.erb
<div id="<%= dom_id image %>">
  <p>
    <strong>Name:</strong>
    <%= image.name %>
  </p>

  <p>
    <strong>File:</strong>
    <%= image.file %>
  </p>

  <p>
    <strong>Ave value:</strong>
    <%= image.ave_value %>
  </p>

  <p>
    <strong>Theme:</strong>
    <%= image.theme_id %>
  </p>

</div>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Show this image", @image %> |
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Images</h1>

<div id="images">
  <% @images.each do |image| %>
    <%= render image %>
    <p>
      <%= link_to "Show this image", image %>
    </p>
  <% end %>
</div>

<%= link_to "New image", new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @image %>

<div>
  <%= link_to "Edit this image", edit_image_path(@image) %> |
  <%= link_to "Back to images", images_path %>

  <%= button_to "Destroy this image", @image, method: :delete %>
</div>